dnf:
  - zsh
  - neovim
  - neofetch
  - inxi
  - minicom
  - wget
  - curl
  - rclone
  - ranger
  - mc
  - restic
  - p7zip
  - p7zip-plugins
  - cryptsetup
  - ncdu
  - tmux
  - btop
  - par2cmdline
  - bat
  - nmap-ncat
  - pandoc
  - ripgrep
  - tig
  - w3m
  - exa
rpm:
  - chezmoi: https://github.com/twpayne/chezmoi/releases/download/v2.33.0/chezmoi-2.33.0-x86_64.rpm
tar:
  - zellij: https://github.com/zellij-org/zellij/releases/download/v0.35.2/zellij-x86_64-unknown-linux-musl.tar.gz
binary:
  - nb: https://raw.github.com/xwmx/nb/master/nb
  - host-spawn: https://github.com/1player/host-spawn/releases/download/1.4.1/host-spawn-x86_64

